// Generated by scripts/import-sprites.mjs. Artwork remains a first-version candidate.
export const spriteCatalog:Record<string,{height:number}>={
  "cidadao-comum": {
    "height": 128
  },
  "mendigo": {
    "height": 128
  },
  "viciado-em-bet": {
    "height": 129
  },
  "clt-cansado": {
    "height": 132
  },
  "motogirl": {
    "height": 135
  },
  "pedreiro": {
    "height": 132
  },
  "vizinha-fofoqueira": {
    "height": 144
  },
  "tio-do-churrasco": {
    "height": 144
  },
  "maromba": {
    "height": 144
  },
  "feirante": {
    "height": 144
  },
  "tecnico-ti": {
    "height": 145
  },
  "streamer": {
    "height": 144
  },
  "coach": {
    "height": 111
  },
  "faxineira": {
    "height": 120
  },
  "concurseira": {
    "height": 120
  },
  "vendedor-praia": {
    "height": 117
  },
  "tia-festa": {
    "height": 120
  },
  "roqueira": {
    "height": 120
  },
  "pagodeiro": {
    "height": 146
  },
  "caca-promocao": {
    "height": 144
  },
  "gambiarreiro": {
    "height": 135
  },
  "universitario": {
    "height": 146
  },
  "passageira": {
    "height": 127
  },
  "porteiro": {
    "height": 134
  },
  "goleira": {
    "height": 102
  },
  "sensei": {
    "height": 112
  },
  "merendeira": {
    "height": 103
  },
  "rei-pastel": {
    "height": 104
  },
  "astrologa": {
    "height": 106
  },
  "rei-arraia": {
    "height": 109
  },
  "mae-pet": {
    "height": 133
  },
  "aposentado": {
    "height": 111
  },
  "salva-vidas": {
    "height": 114
  },
  "conspiracionista": {
    "height": 147
  },
  "gamer-mobile": {
    "height": 144
  },
  "rainha-bateria": {
    "height": 146
  }
};
