/** Generated content: per-class funny lines (VGM-053A). Visible text pt-BR. */
export type Situation='levelUp'|'down'|'revive'|'upgrade'|'win'|'lose';
export const CLASS_LINES:Readonly<Record<string,Readonly<Record<Situation,readonly string[]>>>>={
  'cidadao-comum':{
    levelUp:['Subi de nível sem querer.','Nem sei o que fiz, mas valeu!'],
    down:['Tropecei na sacola! Me ajuda!','Me levanta, o pão tá esfriando!'],
    revive:['De pé! Tem pão pra todo mundo.','Ajudei! Posso ir embora agora?'],
    upgrade:['Vou nessa, parece honesto.','Cabe na sacola? Então levo.'],
    win:['Síndico vencido. Agora a padaria.','Bom, já que tô aqui... uhul?'],
    lose:['Devia ter pedido delivery.','Amanhã compro pão mais perto.'],
  },
  'mendigo':{
    levelUp:['Subi! E ainda achei um parafuso.','Upei na base do reaproveitamento.'],
    down:['Me ajuda, eu sei um atalho!','Me tira daqui, eu conserto tudo!'],
    revive:['Achei você no achados e perdidos!','Novo em folha! Quase. Funciona.'],
    upgrade:['Isso aqui vira coisa boa.','Card usado? Melhor ainda.'],
    win:['Eu disse que aquilo era tesouro!','O síndico caiu no meu atalho.'],
    lose:['Guardei uns trecos pra próxima.','Dessa derrota eu faço uma estante.'],
  },
  'viciado-em-bet':{
    levelUp:['Eu falei que ia bater! Eu falei!','Subi! Pura estatística, juro.'],
    down:['Era 1% de chance... saiu o 1%.','Calculei tudo, menos o chão!'],
    revive:['Apostei em você e deu green!','Resgate garantido. Sem zebra.'],
    upgrade:['All-in nesse card!','Pela estatística, é esse aqui.'],
    win:['Eu calculei! Tá, eu chutei.','Cravei o placar, galera!'],
    lose:['Moral: aposta não é plano.','Lição: a casa sempre ganha.'],
  },
  'clt-cansado':{
    levelUp:['Subi de cargo e o salário igual.','Promoção? Vai ter reunião disso?'],
    down:['Vou pedir atestado...','Me acorda às 18h, por favor.'],
    revive:['Levanta, ainda não bateu o ponto!','Bora, que o café ainda tá quente.'],
    upgrade:['Esse card podia ser um e-mail.','Pego esse e saio às 18h.'],
    win:['Sextou com S de síndico!','Agora sim: férias vencidas!'],
    lose:['Pelo menos amanhã é feriado?','Segunda-feira foi mais difícil.'],
  },
  'motogirl':{
    levelUp:['Subi de nível e de cilindrada!','Nota 5 estrelas na entrega!'],
    down:['Pneu furou! Alguém me busca!','Caí no quebra-molas, socorro!'],
    revive:['Entrega feita! Assina aqui.','Chegou seu pedido: uma vida!'],
    upgrade:['Esse vai no baú.','Confirmo o pedido, pode mandar.'],
    win:['Síndico entregue com sucesso!','Avalia a corrida, hein!'],
    lose:['Pedido cancelado pelo cliente.','Endereço não encontrado...'],
  },
  'pedreiro':{
    levelUp:['Subiu mais um andar na laje!','Subi igual parede: no prumo!'],
    down:['Desabei! Alguém escora aqui!','Me ajuda, a fundação cedeu!'],
    revive:['Rebocado e pronto pra outra!','Levantei você melhor que muro.'],
    upgrade:['Esse material é de primeira.','Esse aí eu instalo até segunda.'],
    win:['Demoli o síndico sem alvará!','Obra entregue! Só faltou o rodapé.'],
    lose:['A estrutura tava comprometida.','Faltou material, eu avisei.'],
  },
  'vizinha-fofoqueira':{
    levelUp:['Subi! Mas não conta pra ninguém.','Ai, já fiquei sabendo que upamos.'],
    down:['Me levanta que eu tenho babado!','Socorro! E nem contei o melhor!'],
    revive:['Levanta, que a história é longa.','Te salvei. Agora todo mundo sabe.'],
    upgrade:['Esse card tava na boca do povo.','Peguei esse, e vou comentar.'],
    win:['Gente, o síndico caiu! Espalha!','Vou contar isso na rua inteira.'],
    lose:['Ninguém pode saber disso...','Que vexame. Fecha a janela.'],
  },
  'tio-do-churrasco':{
    levelUp:['Subiu igual fumaça de carvão!','Upou! Isso pede um churrasco.'],
    down:['Caí! Alguém vira a carne pra mim!','Me levanta, o carvão tá acabando!'],
    revive:['Tá no ponto! Pode servir!','Toma um pão de alho e levanta!'],
    upgrade:['Esse aí tá suculento.','Separa esse que é do tio.'],
    win:['Vitória! Acende a churrasqueira!','Vitória! Sai mais uma picanha!'],
    lose:['Passou do ponto. Queimou tudo.','Ninguém ajudou a virar a carne.'],
  },
  'maromba':{
    levelUp:['Ganhei massa de nível!','Isso que é hipertrofia de XP!'],
    down:['Falhei na última série! Ajuda!','Alguém me dá um spot aqui!'],
    revive:['Levanta! Mais uma, só mais uma!','Bora, sem descanso entre séries!'],
    upgrade:['Mais carga nesse card!','Esse card é pré-treino puro.'],
    win:['Esse boss não treinava perna.','Pump de vitória! Foto no espelho!'],
    lose:['Hoje é dia de descanso, só isso.','Faltou proteína na equipe.'],
  },
  'feirante':{
    levelUp:['Subiu! Leva dois, paga um!','Olha o nível fresquinho, freguesa!'],
    down:['Socorro! A barraca desabou!','Me levanta que eu faço desconto!'],
    revive:['Levanta, freguês! Tá novinho!','Toma uma fruta e volta pro jogo!'],
    upgrade:['Esse tá madurinho, pode levar.','Escolhi a dedo, igual tomate.'],
    win:['Hoje eu fecho a barraca cedo!','Xepa do síndico! É pra acabar!'],
    lose:['Hoje a feira não rendeu nada.','Sobrou tudo, até a esperança.'],
  },
  'tecnico-ti':{
    levelUp:['Atualização instalada com sucesso.','Patch novo! Nem li as notas.'],
    down:['Travei! Alguém aperta o reset!','Tela azul! Me reinicia aí!'],
    revive:['Desliga e liga de novo!','Pronto, era só o cabo solto.'],
    upgrade:['Avançar, avançar, concluir.','Instalar? Sim, aceito os termos.'],
    win:['Síndico formatado com sucesso.','Abre um chamado: boss resolvido.'],
    lose:['Erro 404: equipe não encontrada.','Vou ter que restaurar o backup.'],
  },
  'streamer':{
    levelUp:['Chat, upamos! Solta o emote!','Meta da live batida, galera!'],
    down:['Chat, alguém manda ajuda!','Caí! Mas foi pelo conteúdo.'],
    revive:['Clipa esse resgate, chat!','Salvamento ao vivo, sem corte!'],
    upgrade:['O chat escolheu, eu só obedeço.','Esse card é conteúdo puro.'],
    win:['Clipa! Clipa! Clipa tudo!','Melhor live da minha vida, mãe!'],
    lose:['Ok chat, vamos fingir que não.','A live caiu. Tudo culpa do chat.'],
  },
  'coach':{
    levelUp:['Você não upou, você evoluiu.','Gratidão por esse nível!'],
    down:['Isso não é queda, é aprendizado!','Me levanta que eu viro case!'],
    revive:['Levanta! Sai da zona de conforto!','Ressignifica essa queda, campeão!'],
    upgrade:['Esse card vibra na frequência.','Escolhi com o mindset certo.'],
    win:['Manifestei essa vitória!','Agora vira palestra de 3 horas.'],
    lose:['Não perdemos: ganhamos lição.','Derrota é só sucesso adiado.'],
  },
  'faxineira':{
    levelUp:['Subi! E já passei pano no nível.','Até o XP tá brilhando agora.'],
    down:['Escorreguei no chão molhado!','Me levanta, a placa tava ali!'],
    revive:['Levanta e não suja mais, hein!','Tirei você do chão igual poeira.'],
    upgrade:['Esse card tá limpinho, levo.','Vou passar o rodo nesse card.'],
    win:['Pronto. Agora tira o sapato.','Varri o síndico pra fora!'],
    lose:['Quem vai limpar essa bagunça?','Deixa que amanhã eu varro.'],
  },
  'concurseira':{
    levelUp:['Aprovada! Quer dizer, upada.','Nível novo, edital novo.'],
    down:['Caí na pegadinha da banca!','Recurso! Quero recurso, gente!'],
    revive:['Convocada de volta! Toma posse!','Levanta, a nomeação saiu!'],
    upgrade:['Esse card cai muito na prova.','Marquei a alternativa C.'],
    win:['Aprovada em primeiro lugar!','Gabarito oficial: síndico já era.'],
    lose:['Ano que vem tem outro edital.','Faltou meio ponto. De novo.'],
  },
  'vendedor-praia':{
    levelUp:['Olha o nível geladinho!','Subiu! Vai um mate pra comemorar?'],
    down:['Socorro! Derreteu tudo!','Caí na areia quente! Me tira!'],
    revive:['Toma uma água e levanta, chefia!','Reanimado com picolé de limão!'],
    upgrade:['Esse é o mais pedido da areia.','Esse sai mais que picolé!'],
    win:['Vitória! A rodada de água é minha!','Hoje o sol tá pra gente!'],
    lose:['Choveu. Dia perdido, galera.','Nem o protetor salvou.'],
  },
  'tia-festa':{
    levelUp:['Ai, que lindo! Cresceu tanto!','Mandei no grupo da família!'],
    down:['Ai, minha pressão! Me acode!','Alguém traz um copo de água?'],
    revive:['Levanta, menino! Tem bolo ainda!','De pé! A festa nem começou!'],
    upgrade:['Esse eu guardo na bolsa.','Esse vai no guardanapo.'],
    win:['Bora pra pista, até o síndico!','E o casamento, quando sai, hein?'],
    lose:['Leva um docinho pra consolar.','Pelo menos a comida tava boa.'],
  },
  'roqueira':{
    levelUp:['Aumenta o volume desse nível!','Subiu meio tom! Rock!'],
    down:['Arrebentou a corda! Ajuda!','Caí no mosh! Me levanta!'],
    revive:['Levanta e faz o chifrinho!','Ressuscitou no refrão!'],
    upgrade:['Pedal de distorção novo!','Esse card é mais pesado. Quero.'],
    win:['Bis! Bis! Bis!','O síndico pediu pra abaixar. Não!'],
    lose:['Microfonia geral. Acabou.','Cortaram a luz do palco.'],
  },
  'pagodeiro':{
    levelUp:['Subiu o tom! Bora, rapaziada!','Nível novo, mesmo cavaquinho.'],
    down:['Caí! Segura o pandeiro pra mim!','Alguém puxa o refrão por mim...'],
    revive:['Levanta que o pagode não parou!','Deixa acontecer... e aconteceu!'],
    upgrade:['Esse card tem suingue.','Vou nesse, sem pressa nenhuma.'],
    win:['Fecha a roda, foi lindo!','Mais uma! Essa é pro síndico!'],
    lose:['Guarda o cavaco, acabou a roda.','Desafinou geral no final.'],
  },
  'caca-promocao':{
    levelUp:['Upei com 50% de desconto!','Nível novo com frete grátis!'],
    down:['Caí! Tem cashback de vida?','Me ajuda, eu divido em 10x!'],
    revive:['Resgate com 100% de desconto!','Te salvei no precinho!'],
    upgrade:['Só pego se tiver desconto.','Esse tava em promoção relâmpago.'],
    win:['Vitória pela metade do preço!','Síndico em liquidação total!'],
    lose:['Era golpe. O cupom era falso.','Saiu caro. Muito caro.'],
  },
  'gambiarreiro':{
    levelUp:['Subiu! Não encosta que cai.','Nível novo preso com arame.'],
    down:['A fita soltou! Alguém cola eu!','Caí! Mas era temporário...'],
    revive:['Remendei. Não mexe muito.','Funciona! Não sei como, mas vai!'],
    upgrade:['Esse card encaixa com jeitinho.','Dá pra adaptar. Tudo dá.'],
    win:['Venceu com clipe e fita crepe!','Era provisório e ganhou o jogo!'],
    lose:['Um parafuso sobrou. Era esse.','Faltou só uma abraçadeira.'],
  },
  'universitario':{
    levelUp:['Subi de período sem DP!','Nível novo às 23h58. Ufa.'],
    down:['Desmaiei de sono, me acorda!','Me ajuda, o prazo é hoje!'],
    revive:['Levanta, a gente apresenta junto!','Te coloquei no trabalho em grupo!'],
    upgrade:['Escolhi no chute, mas confio.','Esse card vale ponto extra?'],
    win:['Entregue às 23h59! Aprovado!','Agora eu durmo três dias.'],
    lose:['Vou pedir prorrogação do prazo.','Tranquei a matrícula do jogo.'],
  },
  'passageira':{
    levelUp:['Subi! Achei até lugar sentada!','Passei a catraca do nível!'],
    down:['Perdi o equilíbrio! Me segura!','Socorro! Puxa a cordinha!'],
    revive:['Levanta, que o ponto é o próximo!','Cabe mais um! Sobe, sobe!'],
    upgrade:['Esse card vai no colo.','Com licença, esse é meu.'],
    win:['Chegamos no ponto final!','Motorista, pode abrir atrás!'],
    lose:['Perdi o último busão...','Desce todo mundo, quebrou.'],
  },
  'porteiro':{
    levelUp:['Nível liberado, pode subir.','Interfonei e mandaram subir!'],
    down:['Alô? Portaria caída! Ajuda!','Alguém assume a guarita?'],
    revive:['Liberado! Tá na lista agora.','Pode entrar, já te conheço.'],
    upgrade:['Esse card tá autorizado.','Deixa que eu recebo esse.'],
    win:['O Síndico Supremo foi despejado!','Agora quem manda é a portaria!'],
    lose:['Deixaram entrar sem interfonar.','Vou ter que registrar ocorrência.'],
  },
  'goleira':{
    levelUp:['Subiu! Bora pro segundo tempo!','Subi de divisão, galera!'],
    down:['Fui driblada! Alguém cobre o gol!','Ai! Pede substituição!'],
    revive:['Defendi você no último lance!','Levanta! Ainda tem os pênaltis!'],
    upgrade:['Pega esse e cola na luva.','Esse eu agarro de primeira.'],
    win:['Gol contra do síndico! Valeu!','Ninguém passou! Nem o síndico!'],
    lose:['Tomei de bico. Que vergonha.','Culpa do juiz, com certeza.'],
  },
  'sensei':{
    levelUp:['Faixa nova! Amarra direitinho.','O aluno virou mestre. Quase.'],
    down:['O mestre caiu... de propósito.','Isso foi um treino! Me levanta!'],
    revive:['Levanta e cumprimenta o tatame.','Postura! Respira! Volta!'],
    upgrade:['Esse golpe eu treino na garagem.','Kata novo desbloqueado.'],
    win:['Chinelada cósmica no síndico!','Oss! Aula encerrada!'],
    lose:['Hoje a lição é a humildade.','Vinte flexões pra cada um.'],
  },
  'merendeira':{
    levelUp:['Subiu! Repete o prato, que é bom!','Nível novo com sobremesa!'],
    down:['Derrubei a panela! Me ajuda!','Caí! Quem vai servir o almoço?'],
    revive:['Toma uma concha de sopa e levanta.','Levanta, que hoje tem feijoada!'],
    upgrade:['Esse vem com arroz e feijão.','Capricha no card, por favor.'],
    win:['Recreio liberado, criançada!','Hoje tem repeteco pra todo mundo!'],
    lose:['A comida esfriou toda...','Ninguém repetiu. Que tristeza.'],
  },
  'rei-pastel':{
    levelUp:['Subiu igual massa no óleo!','Nível novo, saindo quentinho!'],
    down:['Queimei a mão! Me socorre!','Furou o pastel! Ajuda aqui!'],
    revive:['Levanta, crocante de novo!','Te salvei com recheio extra!'],
    upgrade:['Esse card é de queijo?','Pastel de vento não, quero esse!'],
    win:['Rodada de pastel por minha conta!','Vitória sequinha e crocante!'],
    lose:['Murchou que nem pastel frio.','O óleo esfriou. Fecha a barraca.'],
  },
  'astrologa':{
    levelUp:['Os astros alinharam! Subimos!','Júpiter expandiu nosso nível!'],
    down:['Caí! Culpa da lua em escorpião!','Mercúrio me derrubou! Ajuda!'],
    revive:['Seu signo pediu um resgate.','Levanta, que hoje seu dia é bom!'],
    upgrade:['Esse card combina com meu signo.','As cartas indicam... essa aqui.'],
    win:['Tava escrito nas estrelas!','Mapa astral confirmado: vitória!'],
    lose:['Era retrógrado. Não adiantava.','Eu disse pra não sair hoje.'],
  },
  'rei-arraia':{
    levelUp:['Anarriê! Subimos de nível!','Olha o nível! É verdade!'],
    down:['Caí na quadrilha! Me ajuda!','Olha a queda! Não é mentira!'],
    revive:['Balancê! Levantou, minha gente!','Pula a fogueira e volta pro baile!'],
    upgrade:['Esse card ganha prenda!','Esse vai pro correio elegante.'],
    win:['Viva o arraiá da vitória!','Fogueira acesa! Síndico pulou!'],
    lose:['Choveu na festa junina...','Acabou a pamonha e a alegria.'],
  },
  'mae-pet':{
    levelUp:['O neném upou! Que orgulho!','Subiu! Mamãe te dá um petisco.'],
    down:['Caí! Alguém cuida do neném!','Enrosquei na coleira! Socorro!'],
    revive:['Toma um petisco e levanta!','Quem é o bom aventureiro? É você!'],
    upgrade:['Esse card tem cheirinho de pet.','O neném escolheu esse, ó.'],
    win:['Foto do neném com o troféu!','Até o gato ficou impressionado.'],
    lose:['O neném tá triste, gente.','Bora pra casa dar ração pra ele.'],
  },
  'aposentado':{
    levelUp:['No meu tempo subia de escada!','Esse nível eu já tive em 72.'],
    down:['Ai, a coluna! Me ajuda aqui!','Caí! Mas no meu tempo era pior.'],
    revive:['Levanta, moço! Ainda tem dominó.','Te pesquei igual lambari!'],
    upgrade:['Esse eu escolho de olho fechado.','Me lembra minha juventude.'],
    win:['Bati o dominó! Digo, o síndico!','Essa vou contar por 40 anos.'],
    lose:['Vou pro banco da praça, então.','Nos anos 70 a gente ganhava.'],
  },
  'salva-vidas':{
    levelUp:['Subiu a maré do nível!','Bandeira verde! Nível liberado!'],
    down:['Me afogando aqui! Joga a boia!','Quem salva o salva-vidas?'],
    revive:['Resgatado! Respira fundo!','Puxei pela corda! Tá salvo!'],
    upgrade:['Esse card boia, pode pegar.','Esse tem colete incluso.'],
    win:['Síndico levado pela correnteza!','Ninguém se afogou hoje. Uhul!'],
    lose:['Bandeira vermelha pra todo mundo.','Mar revolto demais, galera.'],
  },
  'conspiracionista':{
    levelUp:['Subimos? Conveniente demais...','Querem que a gente suba. Por quê?'],
    down:['Me derrubaram! Foi armação!','Me resgata! Eles têm um plano!'],
    revive:['Te salvei. Eles não esperavam.','Levanta! O sensor apitou!'],
    upgrade:['Esse card tem mensagem oculta.','Lê de trás pra frente: é esse!'],
    win:['O síndico era um robô. Eu sabia!','Isso estava previsto. Por mim.'],
    lose:['O jogo tava viciado, claro.','Os pombos avisaram o boss.'],
  },
  'gamer-mobile':{
    levelUp:['Upei! Mesmo com 3% de bateria!','Subiu! Nem foi o lag dessa vez.'],
    down:['Caí! Foi o ping, juro!','O Wi-Fi caiu, alguém me cobre!'],
    revive:['Revivi pela tela rachada mesmo!','Salvei com o 4G no talo!'],
    upgrade:['Cliquei sem querer, mas tá bom.','Esse card é meta, confia.'],
    win:['GG! Fácil, fácil!','Print! Print! Alguém tira print!'],
    lose:['Meu celular esquentou, não vale.','Desliga que a bateria acabou.'],
  },
  'rainha-bateria':{
    levelUp:['Subiu o samba! Aumenta o surdo!','Nível novo na avenida!'],
    down:['Caí na avenida! Segura o tambor!','Me ajuda, a fantasia enroscou!'],
    revive:['Levanta que a bateria não para!','Recuo de bateria pra te salvar!'],
    upgrade:['Esse entra no samba-enredo!','Adiciona esse no batuque!'],
    win:['Nota dez em todos os quesitos!','Campeã do carnaval da dungeon!'],
    lose:['Estourou o tempo do desfile...','Quarta-feira de cinzas chegou.'],
  },
};
