import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import sharp from 'sharp';

const source=path.resolve(process.argv[2]||'../viagem-trees');
const output=path.resolve('public/art/trees');
await fs.mkdir(output,{recursive:true});
const catalog=[],report=[];
for(let lot=1;lot<=8;lot++){
  const directory=path.join(source,`lote-${lot}`);
  let manifest;try{manifest=JSON.parse(await fs.readFile(path.join(directory,'manifest.json'),'utf8'));}catch(error){if(error.code==='ENOENT')continue;throw error;}
  for(const tree of manifest.trees){
    assert.match(tree.id,/^[a-z0-9-]+$/);
    assert.ok(!catalog.some(t=>t.id===tree.id),'Duplicate tree ID');
    assert.equal(tree.frameWidth,256);assert.equal(tree.frameHeight,384);assert.equal(tree.frames,4);assert.equal(tree.columns,2);
    assert.equal(tree.originX,.5);assert.ok(Math.abs(tree.originY-353/384)<.000001);
    assert.ok(tree.height>=80&&tree.height<=220);
    const file=path.resolve(directory,tree.file);assert.ok(file.startsWith(directory+path.sep));
    const meta=await sharp(file).metadata();assert.equal(meta.width,512);assert.equal(meta.height,768);assert.ok(meta.hasAlpha);
    const frames=[];
    for(let index=0;index<4;index++){
      const {data,info}=await sharp(file).extract({left:index%2*256,top:Math.floor(index/2)*384,width:256,height:384}).ensureAlpha().raw().toBuffer({resolveWithObject:true});
      let left=256,right=-1,top=384,bottom=-1,opaque=0;
      for(let y=0;y<384;y++)for(let x=0;x<256;x++)if(data[(y*256+x)*info.channels+3]>16){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);opaque++;}
      assert.ok(opaque>400&&opaque<256*384*.85,`${tree.id}/${index}: missing cutout`);
      assert.ok(left>=7&&right<=248&&top>=7&&bottom<=376,`${tree.id}/${index}: clipped frame`);
      // Roots can extend below the registered trunk pivot (353).
      assert.ok(bottom>=340,`${tree.id}/${index}: no roots near the ground pivot`);
      frames.push({left,right,top,bottom,hash:createHash('sha256').update(data).digest('hex')});
    }
    assert.equal(new Set(frames.map(f=>f.hash)).size,4,`${tree.id}: duplicated views`);
    const pixelHeight=Math.max(...frames.map(f=>f.bottom-f.top+1)),scale=tree.height/pixelHeight;
    for(const frame of frames){
      assert.ok(Math.max(Math.abs(frame.left-128),Math.abs(frame.right-128))*scale<=160,`${tree.id}: exceeds horizontal framing margin`);
      assert.ok((353-frame.top)*scale<=250,`${tree.id}: exceeds vertical framing margin`);
    }
    const target=path.join(output,`${tree.id}.webp`);
    const exported=await fs.stat(target).catch(()=>null);
    if(!exported||exported.mtimeMs<(await fs.stat(file)).mtimeMs)await sharp(file).webp({lossless:true,effort:6}).toFile(target);
    const name=/[ÃÂ]/.test(tree.name)?Buffer.from(tree.name,'latin1').toString('utf8'):tree.name;
    catalog.push({id:tree.id,name,height:tree.height,pixelHeight,status:tree.status||'candidate'});
    report.push({id:tree.id,lot,frames,issues:tree.issues||[],status:tree.status||'candidate'});
  }
}
await fs.writeFile('src/game/tree-catalog.ts',`export interface TreeArt {id:string;name:string;height:number;pixelHeight:number;status:string}\n// Generated by scripts/import-trees.mjs. Direction order: 0, 90, 180, 270 degrees.\nexport const treeCatalog:TreeArt[]=${JSON.stringify(catalog,null,2)};\n`);
await fs.writeFile(path.join(output,'manifest.json'),JSON.stringify({trees:catalog},null,2)+'\n');
await fs.mkdir('artifacts',{recursive:true});
await fs.writeFile('artifacts/tree-import-report.json',JSON.stringify(report,null,2)+'\n');
console.log(`${catalog.length}/40 trees imported with four distinct transparent frames each.`);
