import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {classes} from '../src/classes.ts';

const root=process.argv[2];
if(!root)throw new Error('Pass the sprite batch directory.');
await mkdir('public/art/sprites',{recursive:true});
await mkdir('artifacts',{recursive:true});
const report=[],catalog={};
for(const [i,hero] of classes.entries()){
  const batch=path.join(root,`lote-${Math.floor(i/6)+1}`),dir=path.join(batch,hero.id);
  const status=JSON.parse(await readFile(path.join(dir,'status.json'),'utf8'));
  let source;
  try{const meta=JSON.parse(await readFile(path.join(dir,'atlas.json'),'utf8'));source=path.join(dir,meta.image);}catch{
    const file=status.files.atlas;
    for(const candidate of [path.join(dir,file),path.join(batch,file)])try{await stat(candidate);source=candidate;break;}catch{}
  }
  if(!source)throw new Error(`Missing atlas: ${hero.id}`);
  const meta=await sharp(source).metadata();
  if(meta.width!==1152||meta.height!==576||!meta.hasAlpha)throw new Error(`Invalid sheet: ${hero.id}`);
  let standingHeight=0;
  for(let frame=0;frame<18;frame++){
    const alpha=await sharp(source).extract({left:frame%6*192,top:Math.floor(frame/6)*192,width:192,height:192}).extractChannel('alpha').raw().toBuffer();
    let minY=192,maxY=-1,transparent=0,occupied=0;
    for(let y=0;y<192;y++)for(let x=0;x<192;x++){const a=alpha[y*192+x];if(a===0)transparent++;if(a>20){occupied++;minY=Math.min(minY,y);maxY=Math.max(maxY,y);if(x===0||x===191||y===0||y===191)throw new Error(`Clipped cell: ${hero.id}:${frame}`);}}
    if(!occupied||!transparent)throw new Error(`Empty or opaque frame: ${hero.id}:${frame}`);
    if(frame===0)standingHeight=maxY-minY+1;
  }
  const output=`public/art/sprites/${hero.id}.webp`;
  await sharp(source).webp({lossless:true,effort:6}).toFile(output);
  catalog[hero.id]={height:standingHeight};
  report.push({id:hero.id,source,output,bytes:(await stat(output)).size,frames:18,artStatus:'candidate',issues:status.remainingIssues??status.remainingProblems??status.issues??[]});
}
await writeFile('src/game/sprite-catalog.ts',`// Generated by scripts/import-sprites.mjs. Artwork remains a first-version candidate.\nexport const spriteCatalog:Record<string,{height:number}>=${JSON.stringify(catalog,null,2)};\n`);
await writeFile('artifacts/sprite-import-report.json',JSON.stringify(report,null,2));
console.log(JSON.stringify({classes:report.length,frames:report.length*18,bytes:report.reduce((n,r)=>n+r.bytes,0)}));
