export type Role = 'Linha de frente' | 'Dano' | 'Suporte' | 'Controle';
export interface HeroClass {
  id: string; name: string; subtitle: string; role: Role; description: string;
  skill: string; skillDescription: string; stats: [number, number, number, number];
  quote: string; art: number;
}
// Atlas: 6 colunas × 6 linhas. A ordem é um contrato com o prompt da arte.
export const classes: HeroClass[] = [
  {id:'cidadao-comum',name:'Cidadão Comum',subtitle:'O básico também dá crítico.',role:'Linha de frente',description:'Saiu para comprar pão e entrou numa missão de nível impossível. Não tem superpoder, mas trouxe uma sacola.',skill:'Só Estou de Passagem',skillDescription:'Avança protegendo aliados próximos. Quanto mais confusão, maior sua resistência.',stats:[3,3,3,3],quote:'Eu só queria chegar em casa.',art:0},
  {id:'mendigo',name:'Mendigo',subtitle:'Improviso lendário.',role:'Suporte',description:'Conhece cada atalho e transforma o que o resto do mundo ignora em equipamento indispensável para a turma.',skill:'Tesouro do Achados',skillDescription:'Monta um abrigo improvisado que protege e recupera aliados na área.',stats:[2,3,4,3],quote:'Isso aqui ainda dá jogo.',art:1},
  {id:'viciado-em-bet',name:'Viciado em Bet',subtitle:'A sorte não leu o tutorial.',role:'Dano',description:'Fala em probabilidade o tempo inteiro. Seus palpites mágicos oscilam, mas nunca colocam a vida da equipe em aposta.',skill:'Odd Impossível',skillDescription:'Lança dados mágicos: causa dano básico garantido e um bônus variável. Usa apenas energia fictícia do jogo.',stats:[4,2,5,1],quote:'Dessa vez é certeza. Eu acho.',art:2},
  {id:'clt-cansado',name:'CLT Cansado',subtitle:'Tanque em horário comercial.',role:'Linha de frente',description:'Sobreviveu a reuniões que poderiam ser mensagens. Um monstro gigante não chega nem perto da segunda-feira.',skill:'Hora Extra',skillDescription:'Recebe um escudo temporário e atrai inimigos enquanto o café estiver fazendo efeito.',stats:[5,1,3,3],quote:'Isso entra no banco de horas?',art:3},
  {id:'motogirl',name:'Motogirl',subtitle:'Sua salvação saiu para entrega.',role:'Suporte',description:'Encontra qualquer endereço, inclusive uma masmorra sem número. Chega primeiro e nunca esquece o pedido.',skill:'Entrega Expressa',skillDescription:'Corre até um aliado e entrega cura; o percurso deixa um rastro de velocidade.',stats:[2,5,2,3],quote:'Tô na porta. Qual é o portão?',art:4},
  {id:'pedreiro',name:'Pedreiro',subtitle:'A obra é a defesa.',role:'Linha de frente',description:'Olhou para o chefe e disse que a estrutura está comprometida. Faz uma muralha antes de o cimento secar.',skill:'Puxadinho Tático',skillDescription:'Ergue uma barreira temporária que bloqueia inimigos e protege a retaguarda.',stats:[5,1,4,2],quote:'Dá pra fazer. Só falta material.',art:5},
  {id:'vizinha-fofoqueira',name:'Vizinha Fofoqueira',subtitle:'Informação privilegiada.',role:'Controle',description:'Sabe quem entrou na dungeon, com quem saiu e por que o boss está nervoso. Seu alcance é a rua inteira.',skill:'Já Fiquei Sabendo',skillDescription:'Revela inimigos próximos e marca o alvo principal para a equipe causar mais dano.',stats:[1,3,5,3],quote:'Não sou de falar, mas...',art:6},
  {id:'tio-do-churrasco',name:'Tio do Churrasco',subtitle:'O suporte está no ponto.',role:'Suporte',description:'Onde a turma vê uma invasão, ele vê uma desculpa para reunir todo mundo. Carrega carvão para emergências.',skill:'Ponto Perfeito',skillDescription:'Prepara uma área de descanso que cura lentamente e concede força aos aliados.',stats:[3,1,3,5],quote:'Quem pediu bem passado?',art:7},
  {id:'maromba',name:'Maromba',subtitle:'Hoje é treino de chefe.',role:'Dano',description:'Conta repetições até durante o combate. A mochila só tem creatina, uma coqueteleira e convicção.',skill:'Última Repetição',skillDescription:'Carrega um golpe corpo a corpo que empurra inimigos e quebra sua defesa.',stats:[5,3,1,3],quote:'Tá leve! Tá leve!',art:8},
  {id:'feirante',name:'Feirante',subtitle:'Três buffs por um.',role:'Suporte',description:'Sua voz atravessa o mapa. Nunca deixa a equipe sem recursos e conhece o preço de cada relíquia.',skill:'É Pra Acabar',skillDescription:'Distribui frutas que restauram energia e remove um efeito negativo dos aliados próximos.',stats:[2,2,3,5],quote:'Olha a promoção da cura!',art:9},
  {id:'tecnico-ti',name:'Técnico de TI',subtitle:'Já tentou reviver de novo?',role:'Controle',description:'Chega com um cabo que ninguém pediu e resolve o problema. Suspeita que os monstros estejam sem atualização.',skill:'Reinicia Isso',skillDescription:'Solta um pulso que interrompe ataques inimigos e desacelera a área.',stats:[1,3,5,3],quote:'Na minha máquina não tinha dragão.',art:10},
  {id:'streamer',name:'Streamer',subtitle:'A live não pode cair.',role:'Dano',description:'Comenta cada movimento como se milhares estivessem assistindo. Talvez estejam. Talvez seja só a mãe.',skill:'Clipa Isso',skillDescription:'Acerta uma sequência à distância; concluir o combo fortalece o próximo ataque aliado.',stats:[3,4,2,3],quote:'Chat, vocês viram isso?!',art:11},
  {id:'coach',name:'Coach Quântico',subtitle:'Destrave seu dano interior.',role:'Suporte',description:'Transforma qualquer derrota em palestra. A turma reclama, mas o megafone faz todo mundo correr mais rápido.',skill:'Mude o Mindset',skillDescription:'Concede velocidade e resistência a controles aos aliados por um curto período.',stats:[1,2,4,5],quote:'O limite é uma crença do boss.',art:12},
  {id:'faxineira',name:'Faxineira',subtitle:'Vai varrer a dungeon.',role:'Controle',description:'Viu a bagunça e resolveu o encontro antes de alguém pedir. Nenhuma gosma passa pela inspeção.',skill:'Passa o Rodo',skillDescription:'Varre inimigos em um arco e limpa áreas perigosas de efeito temporário.',stats:[3,3,4,2],quote:'Acabei de limpar esse chão!',art:13},
  {id:'concurseira',name:'Concurseira',subtitle:'Especialista em decorar padrões.',role:'Controle',description:'Estudou o manual do monstro, o edital e as erratas. Já sabe qual ataque cai mais na prova.',skill:'Questão Anulada',skillDescription:'Interrompe uma habilidade inimiga e reduz seu dano por um instante.',stats:[1,2,5,4],quote:'Esse padrão já caiu em 2018.',art:14},
  {id:'vendedor-praia',name:'Vendedor de Praia',subtitle:'Reforço geladinho.',role:'Suporte',description:'Caminha o dia todo sob o sol, sempre oferecendo exatamente o que alguém está precisando.',skill:'Olha a Água',skillDescription:'Recupera energia da equipe e remove lentidão enquanto atravessa o grupo.',stats:[2,4,2,4],quote:'Vai uma geladinha, aventureiro?',art:15},
  {id:'tia-festa',name:'Tia da Festa',subtitle:'Ninguém fica parado.',role:'Suporte',description:'Entra em qualquer grupo como se conhecesse todo mundo há vinte anos. A bolsa tem uma solução para cada crise.',skill:'Levanta e Vem',skillDescription:'Acelera a recuperação de um aliado caído e fortalece a cura ao redor.',stats:[2,2,3,5],quote:'Come alguma coisa antes de ir!',art:16},
  {id:'roqueira',name:'Roqueira',subtitle:'Distorção em área.',role:'Dano',description:'Carrega um amplificador que certamente viola as regras do condomínio. O solo começa quando o chefe aparece.',skill:'Solo de Respeito',skillDescription:'Emite ondas sonoras em cone, causando dano crescente em inimigos próximos.',stats:[4,3,2,3],quote:'Agora vai entrar a guitarra.',art:17},
  {id:'pagodeiro',name:'Pagodeiro',subtitle:'Sustain no cavaquinho.',role:'Suporte',description:'Mantém o grupo no ritmo mesmo quando a partida vira um caos. Sabe exatamente quando puxar o refrão.',skill:'Deixa Acontecer',skillDescription:'Cria um ritmo que cura aliados aos poucos e aumenta sua recuperação de energia.',stats:[2,2,3,5],quote:'Só mais uma e a gente vai.',art:18},
  {id:'caca-promocao',name:'Caça-Promoção',subtitle:'Economia de cooldown.',role:'Controle',description:'Consegue desconto até no dano recebido. Seu inventário foi comprado pela metade do preço.',skill:'Cupom Acumulado',skillDescription:'Marca uma área: habilidades de aliados ali recuperam parte da energia utilizada.',stats:[1,4,4,3],quote:'Espera, eu tenho um cupom.',art:19},
  {id:'gambiarreiro',name:'Gambiarreiro',subtitle:'Temporário há seis anos.',role:'Controle',description:'Seu equipamento desafia a física e o bom senso. Se está funcionando, ninguém toca.',skill:'Fita Resolve',skillDescription:'Monta uma armadilha que prende os primeiros inimigos que atravessarem a área.',stats:[3,2,5,2],quote:'Agora segura aqui um pouquinho.',art:20},
  {id:'universitario',name:'Universitário Virado',subtitle:'Entrega às 23h59.',role:'Dano',description:'Não dormiu, mas fez uma apresentação convincente. Canaliza todo o desespero em rajadas de energia.',skill:'Prazo Final',skillDescription:'Dispara rapidamente por um curto período e precisa recuperar o fôlego depois.',stats:[3,4,4,1],quote:'Dá tempo. Ainda dá tempo.',art:21},
  {id:'passageira',name:'Passageira do Busão',subtitle:'Esquiva em horário de pico.',role:'Linha de frente',description:'Aprendeu a manter o equilíbrio nas condições mais improváveis. Não perde a viagem por causa de monstro.',skill:'Dá Licença',skillDescription:'Abre passagem entre inimigos, reduzindo dano recebido durante o movimento.',stats:[3,5,2,2],quote:'Vai descer? Então deixa eu passar.',art:22},
  {id:'porteiro',name:'Porteiro',subtitle:'Entrada só com autorização.',role:'Linha de frente',description:'Reconhece todo mundo da rua, inclusive aquele inimigo disfarçado. Guarda a linha de frente com tranquilidade.',skill:'Nome na Lista',skillDescription:'Provoca um grupo de inimigos e cria uma zona que reduz sua velocidade.',stats:[4,1,4,3],quote:'Vou precisar confirmar lá em cima.',art:23},
  {id:'goleira',name:'Goleira de Várzea',subtitle:'Aqui não passa nada.',role:'Linha de frente',description:'Defende o impossível com uma luva furada. Sua área é o lugar mais seguro do mapa.',skill:'Muralha do Bairro',skillDescription:'Bloqueia projéteis pela frente e protege aliados posicionados atrás dela.',stats:[4,5,1,2],quote:'Essa era minha!',art:24},
  {id:'sensei',name:'Sensei do Bairro',subtitle:'Disciplina e chinelada cósmica.',role:'Dano',description:'Dá aula na garagem e treina até no ponto de ônibus. Seus combos são mais sérios que a faixa amarrada.',skill:'Combo da Garagem',skillDescription:'Executa três golpes próximos; o último atordoa se os anteriores acertarem.',stats:[4,4,2,2],quote:'Respira. Agora desvia.',art:25},
  {id:'merendeira',name:'Merendeira',subtitle:'A cura vem de concha.',role:'Suporte',description:'Conhece todo mundo pelo prato favorito. Com uma panela resolve fome, medo e a moral do grupo.',skill:'Prato Reforçado',skillDescription:'Cura um aliado e concede vida temporária que desaparece ao fim do efeito.',stats:[3,1,3,5],quote:'Você tá muito magrinho, vem cá.',art:26},
  {id:'rei-pastel',name:'Rei do Pastel',subtitle:'Crocância ofensiva.',role:'Dano',description:'Conquistou a praça pela qualidade e a dungeon por acidente. Nunca deixa o recheio para depois.',skill:'Óleo no Fogo',skillDescription:'Arremessa um pacote fumegante que causa dano em área e deixa o chão perigoso.',stats:[4,2,3,3],quote:'Saiu um especial da casa!',art:27},
  {id:'astrologa',name:'Astróloga',subtitle:'Seu ascendente é stun.',role:'Controle',description:'Diz que o chefe está agressivo por causa dos astros. Sua previsão é surpreendentemente útil no combate.',skill:'Mercúrio Retrógrado',skillDescription:'Cria um campo que desacelera inimigos e atrasa suas próximas habilidades.',stats:[2,2,5,3],quote:'Eu avisei no mapa astral.',art:28},
  {id:'rei-arraia',name:'Rei do Arraiá',subtitle:'Pula a fogueira, chefão.',role:'Controle',description:'Só precisava de uma sanfona para levantar a turma. Já decorou a masmorra com bandeirinhas.',skill:'Olha a Cobra',skillDescription:'Assusta inimigos próximos e abre espaço para o grupo se reorganizar.',stats:[3,2,2,5],quote:'É mentira! Ou será que não?',art:29},
  {id:'mae-pet',name:'Mãe de Pet',subtitle:'Companheiro inseparável.',role:'Suporte',description:'Trouxe petisco, água, remédio e uma foto do gato para cada pessoa da equipe.',skill:'Cadê o Neném',skillDescription:'Envia um companheiro para buscar um recurso de cura e revelar ameaças próximas.',stats:[1,3,3,5],quote:'Ele não morde. Normalmente.',art:30},
  {id:'aposentado',name:'Aposentado da Praça',subtitle:'Experiência não falta.',role:'Controle',description:'Tem uma história para cada inimigo e uma estratégia que parece absurda até funcionar.',skill:'No Meu Tempo',skillDescription:'Usa a vara para puxar um inimigo leve e interromper sua aproximação.',stats:[3,1,5,3],quote:'Antigamente o boss era maior.',art:31},
  {id:'salva-vidas',name:'Salva-Vidas',subtitle:'Resgate sem drama.',role:'Suporte',description:'Fica de olho em quem se afasta do grupo. Uma corda e uma boia são suficientes para mudar o combate.',skill:'Segura a Boia',skillDescription:'Protege um aliado distante e o ajuda a escapar de uma área perigosa.',stats:[3,4,2,3],quote:'Não entra aí sem saber nadar!',art:32},
  {id:'conspiracionista',name:'Conspiracionista',subtitle:'Ele sabe demais. Talvez.',role:'Controle',description:'Ligou todos os pontos, inclusive os que não existiam. Pelo menos colocou sensores em volta do acampamento.',skill:'Eu Já Sabia',skillDescription:'Instala um sensor que revela inimigos e avisa a equipe quando uma ameaça se aproxima.',stats:[1,3,5,3],quote:'Isso tudo é um grande tutorial.',art:33},
  {id:'gamer-mobile',name:'Gamer de Celular',subtitle:'A culpa é sempre do ping.',role:'Dano',description:'Usa quatro dedos, duas desculpas e um aparelho com a tela rachada. Não perde um combo quando o Wi-Fi ajuda.',skill:'Modo Tryhard',skillDescription:'Ganha velocidade de ataque ao acertar alvos consecutivos, perdendo o bônus ao errar.',stats:[3,5,3,1],quote:'Tô lagado! Mas eu vi que acertou.',art:34},
  {id:'rainha-bateria',name:'Rainha da Bateria',subtitle:'O ritmo empurra a turma.',role:'Dano',description:'Chegou com um tambor e transformou o encontro numa avenida. Cada batida tem hora e endereço.',skill:'Virada de Carnaval',skillDescription:'Solta uma sequência de pulsos ao redor, causando dano e fortalecendo o movimento dos aliados.',stats:[4,3,1,4],quote:'Abre a roda que eu tô chegando!',art:35},
];
export const roles: Role[] = ['Linha de frente','Dano','Suporte','Controle'];
export function getClass(id: string): HeroClass | undefined { return classes.find(hero => hero.id === id); }
export function filterClasses(query: string, role: string): HeroClass[] {
  const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('pt-BR');
  return classes.filter(hero => (role === 'Todas' || hero.role === role) && normalize(`${hero.name} ${hero.skill} ${hero.subtitle}`).includes(normalize(query)));
}
